### ISSUE TITLE
[Question] Is a PAL support planned?

### ISSUE THREAD

**Issue by Fuzzy2319** [lepelog/sslib#107]
I have an hacked wii witch doesn't support NTSC and only support PAL so my question is Have you planned a PAL support for randomizer?

**Comment by harmjan387** [comment]
Do you have usb loading setup on your wii? Since region unlock isnt required there and can run a rando iso anyway

**Comment by Fuzzy2319** [comment]
Ok I didn't know usb loaders can bypass regions restrictions. But my iso is a copy of my original disc witch is a PAL version so I can't create randomized iso.

**Comment by harmjan387** [comment]
Ah yeah that's a problem. we can't give you a NTSC-U 1.0 iso so you'd have to somehow obtain one yourself

**Comment by lepelog** [comment]
Due to version differences (the clip in ancient cistern, but also differences in various internal files) there are no plans to make a PAL version of the randomizer. However, I do want to make the randomizer work with other versions by simply patching them to NTSC 1.0. I'll make a separate issue for that
