### ISSUE TITLE
Tentalus Boss Room Softlock without Goddess Sword

### ISSUE THREAD

**Issue by azer67** [lepelog/sslib#23]
If you defeat Tentalus without the Goddess Sword you cannot escape the room because you cannot hit the goddess crest. A way out needs to be implemented in a way that still allows getting the crest check and beating the dungeon later.

**Comment by lepelog** [comment]
https://github.com/lepelog/sslib/tree/sandship-bossroom-fix seems to work, only problem is, that it's possible to trigger the escape sequence again after defeating tentalus and leaving the dungeon due to no goddess sword. This can be fixed by adding a storyflag, that deactivates the loadingzone behind the boss door (which is already done with the beat sandship storyflag currently).
This enables "tentalus skip RBM" on the main deck too, to skip 99% of the dungeon, although that can be prevented by adding a storyflag requirement to the event, that is set when tentalus dies
