### ISSUE TITLE
Skyloft Academy is inaccessible, can't complete Lumpy Pumpkin side-quest

### ISSUE THREAD

**Issue by OTFree** [lepelog/sslib#69]
Settings: [Skyward Sword Randomizer Version 1.0.4_4ca3862]
Permalink: [gAAABABsAA==]
Seed: [240048]
Hash : [Scrappa Triforce Keese]

Don't know if this is a side-effect of starting with adventure pouch, but Fledge also doesn't give an item now. Gates in Skyloft remain closed for some reason, Skyloft Academy is now permanently locked. When trying to deliver the Pumpkin Soup, the Academy is still locked, making the side-quest impossible to finish.

**Comment by lepelog** [comment]
Meeting fledge at the start opens the gates and the academy, so the only issue is that he doesn't show up.  
I couldn't reproduce it, a few questions:
- are you playing on english? The rando only works on english
- Are you using any cheats? Even if they are most likely unrelated, try turning everything off and start a new game, to see if fledge is there
- are you using a hero mode save file? If yes, try using a completely new file. The randomizer can skip all cutscenes anyway and since you selected the hero mode option, it will act as hero mode
